### ISSUE TITLE
No correct Capture saved, log: DXGI_ERROR_DEVICE_REMOVED

### ISSUE THREAD

**Issue by Andreyogld3d** [baldurk/renderdoc#1119]
**Description**

Hi, i'm trying to save capture using F12 key during running my Direct3D 11 application, but i have no correct capture, also The RenderDoc hangs

**Repro steps**

1) Launch the application
2) Press F12 to save capture

**Environment**

* RenderDoc:
![image](https://user-images.githubusercontent.com/8597425/46402565-c004b580-c708-11e8-97a1-a691336c35ef.png)

* Operating System: Windows 10 X64, Windows 7 X64
* API: Direct3D 11
* GPU nVidia 610(driver last driver 23.03.2018), AMD R7 240(driver 09.2018)

I attached:
[the simple executable](https://github.com/baldurk/renderdoc/files/2441447/TestRenderDoc.zip)
and
[RenderDoc log file and Render Doc Capture file](https://github.com/baldurk/renderdoc/files/2441450/RenderDoc.files.zip)

**Comment by baldurk** [comment]
Hi there, thank you for the comprehensive report. Unfortunately I'm not able to reproduce the crash on my machines. I've tested Win7 GTX 1080, Win10 GTX 970, and Win10 AMD RX 480.

Looking at the capture you provided, I noticed the swapchain and depth buffer have a high MSAA sample count 8x, and they're also set to quality level 32. None of my machines had that many quality levels for MSAA, so I had to reduce it to fit when trying to open it.

The error seems to happen when trying to resolve and readback the backbuffer for the capture's thumbnail. That failure then causes problems reading back the GPU data to include in the capture which causes the captures to be broken and unable to open.

I've uploaded a capture here: [3DMove_working.zip](https://github.com/baldurk/renderdoc/files/2443405/3DMove_working.zip) which is made from my machine working. Can you test to see if you can open that successfully? I expect you will be able to.

Since I can't reproduce the problem, could you try something: Enable the 'Enable API validation' option when launching the program for capture, then attach visual studio to the program *before* capturing. Then hopefully when capturing you should get debug output messages indicating what the problem might be.

From what I've said above I wonder if it's something to do with the MSAA quality settings as I was unable to reproduce the 32 MSAA quality your capture indicated you were using. I'd also be curious to know if the same problem reproduces if you select a different MSAA quality e.g. 0, or if you lower the MSAA level.

**Comment by Andreyogld3d** [comment]
Hi, @baldurk, thank you for your responce.
I can't open your capture: 

![image](https://user-images.githubusercontent.com/8597425/46441547-7ef3bc00-c76f-11e8-9ca7-e7c7006b6f35.png)

Debug output from Visual Studio:
RDOC 006620: [00:25:41]          rdcfile.cpp( 239) - Log     - Opening RDCFile D:/Downloads/3DMove_working.rdc
RDOC 006620: [00:25:41]          rdcfile.cpp( 239) - Log     - Opening RDCFile D:/Downloads/3DMove_working.rdc
RDOC 006620: [00:25:41]     d3d11_replay.cpp(3526) - Error   - Incompatible D3D11 serialise version 16
RDOC 006620: [00:25:41] replay_controller.cpp(1873) - Error   - Couldn't create a replay device :(.
RDOC 006620: [00:25:41] replay_controller.cpp( 188) - Log     - Shutting down replay renderer
> could you try something: Enable the 'Enable API validation' option >when launching the program for capture, then attach visual studio to the program before capturing. Then >hopefully when capturing you should get debug output messages indicating what the problem might be.

Now i can't reproduce it on Windows 7 x64/AMD R7 240, i will try to do it in monday on work computer with nVidia 610.

But i have anoher bug ang hangs, if i use the compute shaders, when can be out of range during using ByteAdressBuffer. In this case The capture will be saved correctly, but during open the capture my computer hangs, and AMD driver will be restarted.

**Comment by baldurk** [comment]
Ah sorry, I captured it with the latest code, so you'd need to download a recent [nightly build](https://renderdoc.org/builds) to open it. I can also capture on v1.1 tomorrow.

If you're having a separate bug I will need more information to reproduce and investigate that, I can't tell what the problem would be from your description. Out of range access should be protected in D3D11 but make sure you don't have any problems reported by the D3D debug layers, as if there are any errors this can cause crashes in RenderDoc which doesn't validate API use itself.

**Comment by Andreyogld3d** [comment]
Hi, @baldurk. 

> Out of range access should be protected in D3D11 but make sure you don't have any problems reported by the D3D debug layers

I have no any error from Direct3D11 Debug Run time, 

> If you're having a separate bug I will need more information to reproduce and investigate that, I can't tell what the problem would be from your description.

I have some result form other test:

qrenderdoc.exe' has exited with code -1 (0xffffffff):
![image](https://user-images.githubusercontent.com/8597425/46461902-91e6aa80-c7c8-11e8-9cff-a957b8569058.png)

I have invalid reading of final Capture:

![image](https://user-images.githubusercontent.com/8597425/46462335-d292f380-c7c9-11e8-9040-c026671f1a25.png)
[I have attached the new minimal applicaton with compute shaders](https://github.com/baldurk/renderdoc/files/2445545/TestRenderDoc2.zip)
[I have attached capture, RenderDoc log, Visual Studio Debug output.](https://github.com/baldurk/renderdoc/files/2445546/RendeDocFiles.zip)

Let me know about any additional information.

**Comment by baldurk** [comment]
In this case, the GPU is hanging because some calls to `DrawIndexedInstancedIndirect` are given invalid parameters. You create one buffer for each `DrawIndexedInstancedIndirect` call, but only the first one gets initialised properly with `UpdateSubresource` and some early `Dispatch` calls. The other buffers are completely uninitialised, so their contents are undefined when you pass them to `DrawIndexedInstancedIndirect`. To catch this kind of bug RenderDoc fills the initial buffer contents with `0xFEFEFEFE` on replay which unfortunately in this case turns into a driver crash due to the huge drawcall.

Also I realise you can't reproduce the original problem at the moment, but when you are able to the VS debug output should come from the 3DMove.exe program. The debug output from qrenderdoc.exe is not useful because everything from there is already contained in the renderdoc log. If you enable API validation and attach to the captured program, you will be able to see the D3D11 debug messages.

**Comment by Andreyogld3d** [comment]
Thanks for your investigation.
>Also I realise you can't reproduce the original problem at the moment

I will try it later on nVidia 610, because the original bug with first application can be reproduced.

>If you enable API validation and attach to the captured program, you will be able to see the D3D11 debug messages.

I know that the problem also on my side.
Ok, I have tried to D3D11_CREATE_DEVICE_DEBUG flags, but I have no any D3D11 Debug Runtime messages. 

So, if you think that is not bug on RederDoc side, i can close issue.

**Comment by baldurk** [comment]
The second bug with computer shaders can be explained I think, let me know if you find you still have problems even after clearing the buffer.

The first bug is still unexplained so I don't know what that is exactly. Specifying `D3D11_CREATE_DEVICE_DEBUG` when initialising D3D with renderdoc won't actually enable the debug mode. Instead you must enable the 'enable API validation' as renderdoc takes control over the debug mode.

If you do that can you paste the output you do get from visual studio? Is it just a generic message like "The GPU took too long to execute the commands so DEVICE_REMOVED happened" ?

**Comment by Andreyogld3d** [comment]
Ok, i will try your steps on Monday with "Enable API Validation" CheckBox on nVidia 610.

**Comment by Andreyogld3d** [comment]
Hi, @baldurk 
1) I have fixed problem on my side with compute shaders, now RenderDoc can show correct capture.

2) I have tested [the original executable file](https://github.com/baldurk/renderdoc/files/2441447/TestRenderDoc.zip) with "Enable API Validation" on nVidia 610, I still have the same problem.

[New RenderDocFiles](https://github.com/baldurk/renderdoc/files/2456383/RenderDoc.files_new.zip)

**Comment by baldurk** [comment]
Hi there, this log you've posted only shows the failure to open the capture from qrenderdoc's side. It's to be expected if you're still hitting a driver crash while capturing, as the texture contents fail to readback and end up being NULL on replay which is invalid.

I've realised though there's actually another step that's needed, as even with API validation enabled by default renderdoc mutes the debug output into visual studio. You'll need to add a code snippet like this to your code to use the renderdoc un-mute it:

```cpp
#include "C:/program files/renderdoc/renderdoc_app.h" // or the path to your renderdoc install

// call this once at startup, e.g. in WinMain
  if(HMODULE rd = GetModuleHandleA("renderdoc.dll"))
  {
    pRENDERDOC_GetAPI get = (pRENDERDOC_GetAPI)GetProcAddress(rd, "RENDERDOC_GetAPI");
    RENDERDOC_API_1_0_0 *rdoc = NULL;
    get(eRENDERDOC_API_Version_1_0_0, (void **)&rdoc);
    rdoc->SetCaptureOptionU32(eRENDERDOC_Option_DebugOutputMute, 0);
  }
```

(You can also find the #include file [on github here](https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/api/app/renderdoc_app.h)).

Then when you run with "Enable API Validation" can you attach visual studio before capturing, and paste any debug output you get including any error messages about device lost. Hopefully this will point the way to what the problem might be.

**Comment by Andreyogld3d** [comment]
Ok,
1) I have added code to my 3DEngine:
```
void RenderBase::InitRenderDoc()
{
#if defined(_WIN32) && defined(USE_RENDERDOC)
	if (HMODULE rd = GetModuleHandleA("renderdoc.dll"))
	{
		Console& console = Console::GetSinglenton();
		pRENDERDOC_GetAPI RENDERDOC_GetAPI = reinterpret_cast<pRENDERDOC_GetAPI>(GetProcAddress(rd, "RENDERDOC_GetAPI"));
		if (!RENDERDOC_GetAPI) {
			console.AddMessage(Console::ERROR_MESSAGE, "RenderDoc: Can't load RENDERDOC_GetAPI function\n");
			return;
		}
		RENDERDOC_API_1_0_0* rdoc = NULL;
		RENDERDOC_GetAPI(eRENDERDOC_API_Version_1_0_0, reinterpret_cast<void **>(&rdoc));
		if (rdoc) {
			console.AddMessage(Console::INFO_MESSAGE, "RenderDoc: SetCaptureOption: DebugOutputMute false\n");
			rdoc->SetCaptureOptionU32(eRENDERDOC_Option_DebugOutputMute, 0);
		}
		else {
			console.AddMessage(Console::ERROR_MESSAGE, "RenderDoc: Can't get RenderDoc API\n");
		}
	}
#endif
}
```
2) Start RenderDoc with "Enable API Validation"
3)  Attach Visual Studio to qrenderdoc.exe and Launch application
4) Press F12

See Protokol.log:
36652:Mon Oct  8 19:30:18 2018 RenderDoc: SetCaptureOption: DebugOutputMute false

I attached [new executable](https://github.com/baldurk/renderdoc/files/2456838/TestRenderDoc_new.zip)
and [RenderDoc files  with Visual Studio Debug Output](https://github.com/baldurk/renderdoc/files/2456839/RenderDoc.files_new.zip)

**Comment by baldurk** [comment]
Thank you for trying this. However you need to attach visual studio to the program being captured: 3DMove.exe. That is because the device removed error is happening inside that program while trying to capture, so I need to understand why it's crashing for you and not for me.

I'm hoping that when you attach to the program and check the D3D debug output, it might give a reason why the DEVICE_REMOVED error is happening.

When capturing, qrenderdoc.exe doesn't do anything at all, so there are no useful errors or warnings from that process. The failure to open the capture in qrenderdoc is just a side-effect - because the capture was produced broken from within 3DMove.exe.

**Comment by Andreyogld3d** [comment]
Yes!
now, I have some errors from Direct3D11 Debug Runtime after Pressing F12.
I have attached  [the modified executable](https://github.com/baldurk/renderdoc/files/2456927/TestRenderDoc_new_update.zip)
 with D3D11_CREATE_DEVICE_DEBUG and Dialog for selection of Screen mode(it can help to attach to the visual studio debugger).
see Visual Studio VS Debug Output2.txt.

**Comment by baldurk** [comment]
Thanks for that, that's what I was looking for.

Unfortunately the bad news is that D3D doesn't give any reason for the device removal:

> RDOC 025468: [20:03:37]     d3d11_device.cpp(1425) - Log     - Starting capture, frame 1255
> RDOC 025468: [20:03:37]     d3d11_device.cpp(1461) - Log     - Finished capture, Frame 1256
> D3D11: Removing Device.
> D3D11 ERROR: ID3D11Device::RemoveDevice: Device removal has been triggered for the following reason (DXGI_ERROR_DEVICE_HUNG: The Device took an unreasonable amount of time to execute its commands, or the hardware crashed/hung. As a result, the TDR (Timeout Detection and Recovery) mechanism has been triggered. The current Device Context was executing commands when the hang occurred. The application may want to respawn and fallback to less aggressive use of the display hardware). [ EXECUTION ERROR #378: DEVICE_REMOVAL_PROCESS_AT_FAULT]
> D3D11 ERROR: ID3D11DeviceContext::Map: Returning DXGI_ERROR_DEVICE_REMOVED, when a Resource was trying to be mapped with READ or READWRITE. [ RESOURCE_MANIPULATION ERROR #2097214: RESOURCE_MAP_DEVICEREMOVED_RETURN]
> RDOC 025468: [20:03:40]     d3d11_device.cpp(1564) - Error   - Couldn't map staging texture to create thumbnail. HRESULT: DXGI_ERROR_DEVICE_REMOVED

My guess is that reading the screenshot has caused some earlier commands to flush to the GPU, and those are actually the ones that failed. If the debug layer can't say why it failed I would really need to be able to reproduce the problem locally to investigate further.

I have only one guess - maybe on the nvidia 610 the copy of the MSAA depth texture to an array texture so that it can be read to disk is taking too long. Due to D3D limitations I need to perform 2048 fullscreen draws to copy out each of the 256 possible stencil values for each of 8 samples. Possibly on the GPU this actually takes several seconds.

I've pushed a commit which forces a flush after copying each sample. If you feel like compiling renderdoc yourself you could try it, but otherwise the next [nightly build](https://renderdoc.org/builds#nightly) will contain this, please try it and let me know if it works for you.

**Comment by Andreyogld3d** [comment]
Thank you @baldurk, I will build RenderDoc later, and will say you about any result.

**Comment by Andreyogld3d** [comment]
Hi, @baldurk, i have tried to use the [Last Build of RenderDoc](https://renderdoc.org/autobuilds/v1.x/2018/RenderDoc_2018_10_09_c1321427_64.zip)
but I have still the same problem, I attached log file and Visual Studio debug output.
[I attached log file and Visual Studio debug output.](https://github.com/baldurk/renderdoc/files/2464540/RenderDoc.files_new2.zip)

**Comment by baldurk** [comment]
Unfortunately I really don't have any more ideas about what could be going wrong. Without being able to reproduce it I can't investigate the problem, and I can't think of anything else to suggest to you to try.

The difference that has been consistent is that in your case your application has initialised MSAA with `SampleDesc.Count = 8` and `SampleDesc.Quality = 32` for the swapchain and depth buffer. But for me it's just `Quality = 0` because no more quality levels are supported. That isn't impossible but it seems strange to me since you're capturing on an GT 610, and I'm using a GTX 1080, I'd expect at least as much support.

I don't know what your program's quality selection does, but could you try override setting `Quality = 0` manually and see if it changes anything? or maybe reduce the `SampleDesc.Count` and see if that makes a difference?

You also mentioned that you couldn't get this on your AMD R7 240, so it might just be a driver bug at the end of the day. If you haven't already you could try updating your graphics drivers.

**Comment by Andreyogld3d** [comment]
Hi, @baldurk 

> I don't know what your program's quality selection does

```
DXGI_FORMAT format = SwapChainDesc.BufferDesc.Format;
			for (int i = D3D11_MAX_MULTISAMPLE_SAMPLE_COUNT; i; --i) {
				UINT Quality = 0;
				hr = pDevice->CheckMultisampleQualityLevels(format, i, &Quality); 
				if (SUCCEEDED(hr) && Quality) {
					Quality--;
#ifdef MAX_MSAA_QUALITY
					Quality = std::min(Quality, MAX_MSAA_QUALITY);
#endif
					msaaQuality = Quality;
					msaaSampleCount = i;
					RenderBase::SetParam(RenderBase::eMsaa);
					SwapChainDesc.SampleDesc.Count = i;
					SwapChainDesc.SampleDesc.Quality = Quality;
					break;
				}
			}
```

I have tried to set manually the maximum Quality MSAA level:

```
//#define MAX_MSAA_QUALITY static_cast<uint>(16)
#define MAX_MSAA_QUALITY static_cast<uint>(0)
...
#ifdef MAX_MSAA_QUALITY
Quality = std::min(Quality, MAX_MSAA_QUALITY);
SwapChainDesc.SampleDesc.Count = i; // 8
SwapChainDesc.SampleDesc.Quality = Quality;
#endif

// RenderTarget texture
#ifdef MAX_MSAA_QUALITY
textureDesc.SampleDesc.Quality = std::min(textureDesc.SampleDesc.Quality, MAX_MSAA_QUALITY);
#endif
```
But i have still the same result.

**Comment by baldurk** [comment]
What happens if you reduce the number of MSAA samples?

I've also just realised checking again that I made a mistake with the previous experimental fix. I added the flush into the functions that copy Tex2DArray->Tex2DMS. But for stencil it has to be processed separately and I didn't have a second flush there. I've pushed a commit there which will add the flush into the stencil pass, maybe that will make a difference.

Sorry for the back and forth but this problem is hard for me to understand and without being able to reproduce it myself all I can do is ask you for information or testing.

**Comment by Andreyogld3d** [comment]
> What happens if you reduce the number of MSAA samples?

The same errors, debug output you can find there: https://github.com/baldurk/renderdoc/issues/1119#issuecomment-428545965

I will test your changes later.

**Comment by Andreyogld3d** [comment]
Hi @baldurk, 
I have good news, I have tested [last version](https://renderdoc.org/autobuilds/v1.x/2018/RenderDoc_2018_10_11_13e03b79_64.zip) . It working fine! Now I can save correct capture on nVidia 610 :)
You can close this issue. Thank you!
