### ISSUE TITLE
Capture of ANGLE-on-Vulkan tests no longer works on Linux

### ISSUE THREAD

**Issue by ShabbyX** [baldurk/renderdoc#2022]
## Description

On Linux, we use RenderDoc on ANGLE-on-Vulkan tests. RenderDoc is built according to the instructions [here](https://chromium.googlesource.com/angle/angle/+/master/doc/DebuggingTips.md#linux). For summary, the GL and GLES capabilities are compiled out due to ANGLE being a GL driver:

```
cmake -DCMAKE_BUILD_TYPE=Release -Bbuild -H. -DENABLE_GLES=OFF -DENABLE_GL=OFF
```

Up to tag v1.8, things worked ok. Switching to tag v1.9 and doing a clean build, capturing tests is flaky. For example, if particular test is run (which finishes quite fast), the following error is generated:

![renderod-failed-capture](https://user-images.githubusercontent.com/1067408/91067590-1df25d00-e601-11ea-9782-8d67dc485b95.png)

## Steps to reproduce

- Download and build ANGLE
- Build renderdoc on Linux according to the instructions above
- Run `./qrenderdoc`
- Use `<path/to/angle/build>/angle_end2end_tests` as Executable Path
- Use `--gtest_filter=MultisampledRenderToTextureES3Test.BlitFramebufferTest/ES3_Vulkan` as command line arguments
- Enable "Queue Capture" from "Frame 0", with "# Frames" 10
- Observe the failure.

Expected behavior at the last step:

- RenderDoc successfully attaches to the program and captures two frames

## Environment

* RenderDoc version: tag v1.9 (vs working tag v1.8). Also tried with ToT (a6871327a) which has the same behavior as v1.9.
* Operating System: Linux (Ubuntu 20.04)
* Graphics API: Vulkan
* cmake arguments: -DCMAKE_BUILD_TYPE=Release -Bbuild -H. -DENABLE_GLES=OFF -DENABLE_GL=OFF

---

Note: if setting up ANGLE is a hassle and the issue is not easy diagnose, I could try to bisect this, but it could take a while.

---

For more info, here's the log from v1.8:

```
Core     PID 765171: [11:52:36]              core.cpp(418) - Log     - RenderDoc v1.8 Linux 64-bit Release (8b491e15300544332f641b8ec025819d6c0855ee) loaded in replay application
Core     PID 765171: [11:52:36]          settings.cpp(459) - Log     - Loading config from /home/<removed>/.renderdoc/renderdoc.conf
UI       PID 765171: [11:52:36]                 unknown(0) - Log     - QRenderDoc initialising.
Core     PID 765171: [11:52:36]        vk_replay.cpp(4104) - Log     - Created device.
Core     PID 765171: [11:52:36]     android_tools.cpp(354) - Log     - Initialising adb using '/usr/bin/adb'
Core     PID 765189: [11:52:39]              core.cpp(418) - Log     - RenderDoc v1.8 Linux 64-bit Release (8b491e15300544332f641b8ec025819d6c0855ee) capturing application
Core     PID 765189: [11:52:39]          settings.cpp(459) - Log     - Loading config from /home/<removed>/.renderdoc/renderdoc.conf
Core     PID 765189: [11:52:39]     posix_libentry.cpp(56) - Log     - Using delay for debugger 0
Core     PID 765189: [11:52:39]     posix_libentry.cpp(69) - Log     - Loading into /home/<removed>/angle/out/dbg/angle_end2end_tests
Core     PID 765189: [11:52:39]           vk_layer.cpp(99) - Log     - Registering Vulkan hooks
Core     PID 765171: [11:52:39]    target_control.cpp(585) - Log     - Got remote handshake: angle_end2end_tests [765189]
Core     PID 765189: [11:52:39]             core.cpp(1719) - Log     - Adding Vulkan device frame capturer for 0x000056067B851D10
Core     PID 765189: [11:52:39]   vk_device_funcs.cpp(786) - Log     - Initialised capture layer in Vulkan instance.
Core     PID 765189: [11:52:39]  vk_device_funcs.cpp(1373) - Log     - physical device 0: GeForce GTX 970 (ver 440.100 patch 0x0) - 10de:13c2
Core     PID 765189: [11:52:39]          vk_core.cpp(1373) - Warning - VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address
Core     PID 765189: [11:52:39]          vk_core.cpp(1373) - Warning - VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address
Core     PID 765189: [11:52:39]          vk_core.cpp(1373) - Warning - VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address
Core     PID 765189: [11:52:39]          vk_core.cpp(1373) - Warning - VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address
Core     PID 765189: [11:52:39]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension] Validation Warning: [ UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xad32db6 | CreateDevice(): Attempting to enable deprecated extension VK_KHR_bind_memory2, but this extension has been promoted to VK_VERSION_1_1.
Core     PID 765189: [11:52:39]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension] Validation Warning: [ UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xad32db6 | CreateDevice(): Attempting to enable deprecated extension VK_KHR_external_memory, but this extension has been promoted to VK_VERSION_1_1.
Core     PID 765189: [11:52:39]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension] Validation Warning: [ UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xad32db6 | CreateDevice(): Attempting to enable deprecated extension VK_KHR_external_semaphore, but this extension has been promoted to VK_VERSION_1_1.
Core     PID 765189: [11:52:39]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension] Validation Warning: [ UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xad32db6 | CreateDevice(): Attempting to enable deprecated extension VK_KHR_get_memory_requirements2, but this extension has been promoted to VK_VERSION_1_1.
Core     PID 765189: [11:52:39]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension] Validation Warning: [ UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xad32db6 | CreateDevice(): Attempting to enable deprecated extension VK_KHR_sampler_ycbcr_conversion, but this extension has been promoted to VK_VERSION_1_1.
Core     PID 765189: [11:52:40]  vk_device_funcs.cpp(3350) - Log     - Created capture device from physical device 0
Core     PID 765189: [11:52:40]          vk_memory.cpp(59) - Log     - Memory type 0: VkMemoryPropertyFlagBits(0) in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) []
Core     PID 765189: [11:52:40]          vk_memory.cpp(59) - Log     - Memory type 1: VkMemoryPropertyFlagBits(0) in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) []
Core     PID 765189: [11:52:40]          vk_memory.cpp(59) - Log     - Memory type 2: VkMemoryPropertyFlagBits(0) in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) []
Core     PID 765189: [11:52:40]          vk_memory.cpp(59) - Log     - Memory type 3: VkMemoryPropertyFlagBits(0) in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) []
Core     PID 765189: [11:52:40]          vk_memory.cpp(59) - Log     - Memory type 4: VkMemoryPropertyFlagBits(0) in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) []
Core     PID 765189: [11:52:40]          vk_memory.cpp(59) - Log     - Memory type 5: VkMemoryPropertyFlagBits(0) in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) []
Core     PID 765189: [11:52:40]          vk_memory.cpp(59) - Log     - Memory type 6: VkMemoryPropertyFlagBits(0) in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) []
Core     PID 765189: [11:52:40]          vk_memory.cpp(59) - Log     - Memory type 7: VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT in heap 0 (VK_MEMORY_HEAP_DEVICE_LOCAL_BIT) (4.0 GB) [GPULocal]
Core     PID 765189: [11:52:40]          vk_memory.cpp(59) - Log     - Memory type 8: VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT in heap 0 (VK_MEMORY_HEAP_DEVICE_LOCAL_BIT) (4.0 GB) []
Core     PID 765189: [11:52:40]          vk_memory.cpp(59) - Log     - Memory type 9: VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) [upload]
Core     PID 765189: [11:52:40]          vk_memory.cpp(59) - Log     - Memory type 10: VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT | VK_MEMORY_PROPERTY_HOST_CACHED_BIT in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) [readback]
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(1622) - Log     - Starting capture, frame 4294967295
Core     PID 765189: [11:52:40]             core.cpp(1751) - Log     - Adding Vulkan frame capturer for 0x000056067B851D10 / 0x0000000009C00002
Core     PID 765189: [11:52:40]          vk_core.cpp(1648) - Log     - Finished capture, Frame 0
Core     PID 765171: [11:52:40]    target_control.cpp(829) - Log     - Used API: Vulkan (Presenting & supported)
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          rdcfile.cpp(1165) - Log     - Finishing write to section 1 (renderdoc/internal/framecapture). Compressed from 6080 bytes to 2786 (45.82 %)
Core     PID 765189: [11:52:40]          vk_core.cpp(2009) - Log     - Captured Vulkan frame with 0.005798 MB capture section in 0.090117 seconds
Core     PID 765189: [11:52:40]          rdcfile.cpp(1165) - Log     - Finishing write to section 7 (renderdoc/internal/exthumb). Compressed from 197 bytes to 197 (100.00 %)
Core     PID 765189: [11:52:40]             core.cpp(1663) - Log     - Written to disk: /tmp/RenderDoc/angle_end2end_tests_2020.08.24_15.52.39_frame0.rdc
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:40]          vk_core.cpp(1622) - Log     - Starting capture, frame 4294967295
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [VUID-VkImageCreateInfo-usage-00968] Validation Error: [ VUID-VkImageCreateInfo-usage-00968 ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x9c8ac9b4 | vkCreateImage(): usage contains VK_IMAGE_USAGE_STORAGE_BIT and the multisampled storage images feature is not enabled, image samples must be VK_SAMPLE_COUNT_1_BIT The Vulkan spec states: If the multisampled storage images feature is not enabled, and usage contains VK_IMAGE_USAGE_STORAGE_BIT, samples must be VK_SAMPLE_COUNT_1_BIT (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkImageCreateInfo-usage-00968)
Core     PID 765189: [11:52:40]           rdcfile.cpp(244) - Log     - Opening RDCFile /tmp/RenderDoc/angle_end2end_tests_2020.08.24_15.52.39_frame0.rdc
Core     PID 765171: [11:52:40]    target_control.cpp(782) - Log     - Got a new capture: 0 (frame 0) (3873 bytes) (time 1598284360) 691 byte thumbnail
Core     PID 765189: [11:52:40]   vk_queue_funcs.cpp(1085) - Log     - Persistent map flush forced for ResourceId::153 (0 -> 33554432)
Core     PID 765189: [11:52:40]   vk_queue_funcs.cpp(1085) - Log     - Persistent map flush forced for ResourceId::153 (1056960 -> 1056964)
Core     PID 765189: [11:52:40]          vk_core.cpp(3493) - Warning - [VUID-VkMappedMemoryRange-size-01390] Validation Error: [ VUID-VkMappedMemoryRange-size-01390 ] Object 0: handle = 0x940000000094, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0xdd4e6d8b | vkFlushMappedMemoryRanges: Size in pMemRanges[0] is 0x4, which is not a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize (0x40). The Vulkan spec states: If size is not equal to VK_WHOLE_SIZE, size must either be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize, or offset plus size must equal the size of memory (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkMappedMemoryRange-size-01390)
Core     PID 765189: [11:52:41]   vk_queue_funcs.cpp(1085) - Log     - Persistent map flush forced for ResourceId::153 (0 -> 1057156)
Core     PID 765189: [11:52:41]          vk_core.cpp(3493) - Warning - [VUID-VkMappedMemoryRange-size-01390] Validation Error: [ VUID-VkMappedMemoryRange-size-01390 ] Object 0: handle = 0x940000000094, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0xdd4e6d8b | vkFlushMappedMemoryRanges: Size in pMemRanges[0] is 0x102184, which is not a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize (0x40). The Vulkan spec states: If size is not equal to VK_WHOLE_SIZE, size must either be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize, or offset plus size must equal the size of memory (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkMappedMemoryRange-size-01390)
Core     PID 765189: [11:52:41]   vk_queue_funcs.cpp(1085) - Log     - Persistent map flush forced for ResourceId::153 (1057344 -> 1057348)
Core     PID 765189: [11:52:41]          vk_core.cpp(3493) - Warning - [VUID-VkMappedMemoryRange-size-01390] Validation Error: [ VUID-VkMappedMemoryRange-size-01390 ] Object 0: handle = 0x940000000094, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0xdd4e6d8b | vkFlushMappedMemoryRanges: Size in pMemRanges[0] is 0x4, which is not a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize (0x40). The Vulkan spec states: If size is not equal to VK_WHOLE_SIZE, size must either be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize, or offset plus size must equal the size of memory (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkMappedMemoryRange-size-01390)
Core     PID 765189: [11:52:42]   vk_queue_funcs.cpp(1085) - Log     - Persistent map flush forced for ResourceId::153 (0 -> 1057540)
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - [VUID-VkMappedMemoryRange-size-01390] Validation Error: [ VUID-VkMappedMemoryRange-size-01390 ] Object 0: handle = 0x940000000094, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0xdd4e6d8b | vkFlushMappedMemoryRanges: Size in pMemRanges[0] is 0x102304, which is not a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize (0x40). The Vulkan spec states: If size is not equal to VK_WHOLE_SIZE, size must either be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize, or offset plus size must equal the size of memory (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkMappedMemoryRange-size-01390)
Core     PID 765189: [11:52:42]          vk_core.cpp(1648) - Log     - Finished capture, Frame 1
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:42]          rdcfile.cpp(1165) - Log     - Finishing write to section 1 (renderdoc/internal/framecapture). Compressed from 35693824 bytes to 160135 (0.45 %)
Core     PID 765189: [11:52:42]          vk_core.cpp(2009) - Log     - Captured Vulkan frame with 34.040283 MB capture section in 1.915789 seconds
Core     PID 765189: [11:52:42]          rdcfile.cpp(1165) - Log     - Finishing write to section 7 (renderdoc/internal/exthumb). Compressed from 197 bytes to 197 (100.00 %)
Core     PID 765189: [11:52:42]             core.cpp(1663) - Log     - Written to disk: /tmp/RenderDoc/angle_end2end_tests_2020.08.24_15.52.39_frame1.rdc
Core     PID 765189: [11:52:42]           rdcfile.cpp(244) - Log     - Opening RDCFile /tmp/RenderDoc/angle_end2end_tests_2020.08.24_15.52.39_frame1.rdc
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - 
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - 
Core     PID 765171: [11:52:42]    target_control.cpp(782) - Log     - Got a new capture: 1 (frame 1) (161222 bytes) (time 1598284362) 691 byte thumbnail
Core     PID 765189: [11:52:42]          vk_core.cpp(1622) - Log     - Starting capture, frame 4294967295
Core     PID 765189: [11:52:42]             core.cpp(1781) - Log     - Removing frame capturer for 0x000056067B851D10 / 0x0000000009C00002
Core     PID 765189: [11:52:42]          vk_core.cpp(3493) - Warning - [VUID-vkDestroyDevice-device-00378] Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x56067bc11630, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0xc900000000c9, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x56067bc11630[], VkDeviceMemory 0xc900000000c9[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
Core     PID 765189: [11:52:42]             core.cpp(1735) - Log     - Removing device frame capturer for 0x000056067B851D10
Core     PID 765189: [11:52:42]          vk_manager.h(200) - Error   - Assertion failed: 'm_InitialContents.empty()'
Core     PID 765189: [11:52:42]          vk_manager.h(201) - Error   - Assertion failed: 'm_ResourceRecords.empty()'
Core     PID 765189: [11:52:42]          vk_manager.h(202) - Error   - Assertion failed: 'm_CurrentResourceMap.empty()'
Core     PID 765189: [11:52:42]              core.cpp(481) - Log     - 'Leaking' unretrieved capture /tmp/RenderDoc/angle_end2end_tests_2020.08.24_15.52.39_frame0.rdc
Core     PID 765189: [11:52:42]              core.cpp(481) - Log     - 'Leaking' unretrieved capture /tmp/RenderDoc/angle_end2end_tests_2020.08.24_15.52.39_frame1.rdc
```

And the log from v1.9:

```
Core     PID 768135: [12:03:08]              core.cpp(418) - Log     - RenderDoc v1.9 Linux 64-bit Release (22dbb188ceac48479764540ee0df3e4f28b6f0b3) loaded in replay application
Core     PID 768135: [12:03:08]          settings.cpp(459) - Log     - Loading config from /home/<removed>/.renderdoc/renderdoc.conf
UI       PID 768135: [12:03:08]                 unknown(0) - Log     - QRenderDoc initialising.
Core     PID 768135: [12:03:08]        vk_replay.cpp(4181) - Log     - Created device.
Core     PID 768135: [12:03:08]     android_tools.cpp(354) - Log     - Initialising adb using '/usr/bin/adb'
Core     PID 768135: [12:03:12]     posix_process.cpp(831) - Log     - Running process /home/<removed>/angle/out/dbg/angle_end2end_tests for injection
Core     PID 768168: [12:03:12]              core.cpp(418) - Log     - RenderDoc v1.9 Linux 64-bit Release (22dbb188ceac48479764540ee0df3e4f28b6f0b3) capturing application
Core     PID 768168: [12:03:12]          settings.cpp(459) - Log     - Loading config from /home/<removed>/.renderdoc/renderdoc.conf
Core     PID 768168: [12:03:12]     posix_libentry.cpp(56) - Log     - Using delay for debugger 0
Core     PID 768168: [12:03:12]     posix_libentry.cpp(69) - Log     - Loading into /home/<removed>/angle/out/dbg/angle_end2end_tests
Core     PID 768168: [12:03:12]           vk_layer.cpp(99) - Log     - Registering Vulkan hooks
Core     PID 768168: [12:03:12]             core.cpp(1757) - Log     - Adding Vulkan device frame capturer for 0x0000560F01E001A0
Core     PID 768168: [12:03:12]   vk_device_funcs.cpp(789) - Log     - Initialised capture layer in Vulkan instance.
Core     PID 768168: [12:03:12]  vk_device_funcs.cpp(1376) - Log     - physical device 0: GeForce GTX 970 (ver 440.100 patch 0x0) - 10de:13c2
Core     PID 768168: [12:03:12]          vk_core.cpp(1392) - Warning - VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address
Core     PID 768168: [12:03:12]          vk_core.cpp(1392) - Warning - VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address
Core     PID 768168: [12:03:12]          vk_core.cpp(1392) - Warning - VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address
Core     PID 768168: [12:03:12]          vk_core.cpp(1392) - Warning - VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension] Validation Warning: [ UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xad32db6 | CreateDevice(): Attempting to enable deprecated extension VK_KHR_bind_memory2, but this extension has been promoted to VK_VERSION_1_1.
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension] Validation Warning: [ UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xad32db6 | CreateDevice(): Attempting to enable deprecated extension VK_KHR_external_memory, but this extension has been promoted to VK_VERSION_1_1.
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension] Validation Warning: [ UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xad32db6 | CreateDevice(): Attempting to enable deprecated extension VK_KHR_external_semaphore, but this extension has been promoted to VK_VERSION_1_1.
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension] Validation Warning: [ UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xad32db6 | CreateDevice(): Attempting to enable deprecated extension VK_KHR_get_memory_requirements2, but this extension has been promoted to VK_VERSION_1_1.
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension] Validation Warning: [ UNASSIGNED-BestPractices-vkCreateDevice-deprecated-extension ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xad32db6 | CreateDevice(): Attempting to enable deprecated extension VK_KHR_sampler_ycbcr_conversion, but this extension has been promoted to VK_VERSION_1_1.
Core     PID 768168: [12:03:12]  vk_device_funcs.cpp(3414) - Log     - Created capture device from physical device 0
Core     PID 768168: [12:03:12]          vk_memory.cpp(59) - Log     - Memory type 0: VkMemoryPropertyFlagBits(0) in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) []
Core     PID 768168: [12:03:12]          vk_memory.cpp(59) - Log     - Memory type 1: VkMemoryPropertyFlagBits(0) in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) []
Core     PID 768168: [12:03:12]          vk_memory.cpp(59) - Log     - Memory type 2: VkMemoryPropertyFlagBits(0) in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) []
Core     PID 768168: [12:03:12]          vk_memory.cpp(59) - Log     - Memory type 3: VkMemoryPropertyFlagBits(0) in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) []
Core     PID 768168: [12:03:12]          vk_memory.cpp(59) - Log     - Memory type 4: VkMemoryPropertyFlagBits(0) in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) []
Core     PID 768168: [12:03:12]          vk_memory.cpp(59) - Log     - Memory type 5: VkMemoryPropertyFlagBits(0) in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) []
Core     PID 768168: [12:03:12]          vk_memory.cpp(59) - Log     - Memory type 6: VkMemoryPropertyFlagBits(0) in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) []
Core     PID 768168: [12:03:12]          vk_memory.cpp(59) - Log     - Memory type 7: VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT in heap 0 (VK_MEMORY_HEAP_DEVICE_LOCAL_BIT) (4.0 GB) [GPULocal]
Core     PID 768168: [12:03:12]          vk_memory.cpp(59) - Log     - Memory type 8: VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT in heap 0 (VK_MEMORY_HEAP_DEVICE_LOCAL_BIT) (4.0 GB) []
Core     PID 768168: [12:03:12]          vk_memory.cpp(59) - Log     - Memory type 9: VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) [upload]
Core     PID 768168: [12:03:12]          vk_memory.cpp(59) - Log     - Memory type 10: VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT | VK_MEMORY_PROPERTY_HOST_CACHED_BIT in heap 1 (VkMemoryHeapFlagBits(0)) (11.7 GB) [readback]
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:12]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:13]             core.cpp(1789) - Log     - Adding Vulkan frame capturer for 0x0000560F01E001A0 / 0x0000000009800002
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkQueueSubmit is called
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - [VUID-VkImageCreateInfo-usage-00968] Validation Error: [ VUID-VkImageCreateInfo-usage-00968 ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x9c8ac9b4 | vkCreateImage(): usage contains VK_IMAGE_USAGE_STORAGE_BIT and the multisampled storage images feature is not enabled, image samples must be VK_SAMPLE_COUNT_1_BIT The Vulkan spec states: If the multisampled storage images feature is not enabled, and usage contains VK_IMAGE_USAGE_STORAGE_BIT, samples must be VK_SAMPLE_COUNT_1_BIT (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkImageCreateInfo-usage-00968)
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkCmdPipelineBarrier is called
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - [UNASSIGNED-BestPractices-pipeline-stage-flags] Validation Warning: [ UNASSIGNED-BestPractices-pipeline-stage-flags ] Object 0: handle = 0x560f021c0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x48a09f6c | You are using VK_PIPELINE_STAGE_ALL_COMMANDS_BIT when vkQueueSubmit is called
Core     PID 768168: [12:03:13]          vk_core.cpp(3563) - Warning - 
Core     PID 768168: [12:03:13]             core.cpp(1819) - Log     - Removing frame capturer for 0x0000560F01E001A0 / 0x0000000009800002
Core     PID 768168: [12:03:13]             core.cpp(1773) - Log     - Removing device frame capturer for 0x0000560F01E001A0
Core     PID 768135: [12:03:13]     linux_process.cpp(378) - Error   - Didn't hit breakpoint in PID 768168 (0)
Core     PID 768135: [12:03:14]     linux_process.cpp(137) - Warning - Couldn't locate renderdoc target control listening port between 38920 and 38927 in /proc/768168/net/tcp
Core     PID 768135: [12:03:14]     linux_process.cpp(143) - Warning - Process 768168 is no longer running - did it exit during initialisation or fail to run?
```

In both cases, the test runs perfectly fine as per the output in the console from which `qrenderdoc` was run.

**Comment by baldurk** [comment]
Looks like the code to calculate the entry point in the target executable was off, not accounting for an ELF offset that allows section virtual addresses to be different from file offsets. The executables I'd tested with seemed to map these to the same place but maybe it depends on the linker or different linker options. That commit should fix it and inject properly.

**Comment by cnorthrop** [comment]
I know this is closed, but I'm still having problems on Linux with all the exact same steps.

Only differences are I'm on Debian instead of Ubuntu, and I pulled the latest v1.x (31b81ade3cf7ee8af836fb48389187d4dfcdb583)

This is printed to the terminal:
```
ERROR: ld.so: object 'librenderdoc.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```
And this is present in the diagnostic log file:
```
Core     PID 1249256: [16:25:20]     linux_process.cpp(392) - Error   - Assertion failed: '(elf_header.e_shentsize) == (sizeof(Elf64_Shdr))' (elf_header.e_shentsize=0, sizeof(Elf64_Shdr)=64)
Core     PID 1249256: [16:25:20]     linux_process.cpp(443) - Error   - Assertion failed: '(ptraceRet) == (0)' (ptraceRet=-1, 0=0)
Core     PID 1249256: [16:25:21]     linux_process.cpp(456) - Error   - Didn't hit breakpoint in PID 1249702 (0)
```
If I turn on the enhanced debug logging added in cc418495516e3beebc3401fe1374ea73bcfb3c28, I get:
```
Core     PID 1255489: [16:49:36]     linux_process.cpp(259) - Log     - Stopping child PID 1255636 at main
Core     PID 1255489: [16:49:36]     linux_process.cpp(497) - Log     - Stopping in main at child for ptracing
Core     PID 1255489: [16:49:36]     linux_process.cpp(503) - Log     - Done PTRACE_TRACEME, raising SIGSTOP
Core     PID 1255489: [16:49:36]     linux_process.cpp(279) - Log     - Child PID 1255636 is stopped in StopAtMainInChild()
Core     PID 1255489: [16:49:36]     linux_process.cpp(288) - Log     - Child PID 1255636 configured to trace exec(). Continuing child
Core     PID 1255489: [16:49:36]     linux_process.cpp(508) - Log     - Resumed after SIGSTOP
Core     PID 1255489: [16:49:36]     linux_process.cpp(310) - Log     - Child PID 1255636 is stopped at execve()
Core     PID 1255489: [16:49:36]     linux_process.cpp(358) - Log     - Child PID 1255636 has exepath /path/to/angle/out/Debug/angle_end2end_tests basePointer 0x56c8e000 and sectionOffset 0x659000
Core     PID 1255489: [16:49:36]     linux_process.cpp(388) - Log     - exepath /path/to/angle/out/Debug/angle_end2end_tests contains sections, rebasing to correct section
Core     PID 1255489: [16:49:36]     linux_process.cpp(392) - Error   - Assertion failed: '(elf_header.e_shentsize) == (sizeof(Elf64_Shdr))' (elf_header.e_shentsize=0, sizeof(Elf64_Shdr)=64)
Core     PID 1255489: [16:49:36]     linux_process.cpp(410) - Log     - Found section in /path/to/angle/out/Debug/angle_end2end_tests from 0x100001000 - 0x1207d410065b620 at offset 0x65a62000659620 containing entry 0x340065a620.
Core     PID 1255489: [16:49:36]     linux_process.cpp(429) - Log     - child process 1255636 executable /path/to/angle/out/Debug/angle_end2end_tests has entry 0065A653572E7C40 at 0x56c8e000 + (0x65a65300cb2c40 - 0x659000)
Core     PID 1255489: [16:49:36]     linux_process.cpp(437) - Log     - Read word ffffffffffffffff from 0065A653572E7C40 in child process 1255636 running executable /path/to/angle/out/Debug/angle_end2end_tests
Core     PID 1255489: [16:49:36]     linux_process.cpp(443) - Error   - Assertion failed: '(ptraceRet) == (0)' (ptraceRet=-1, 0=0)
Core     PID 1255489: [16:49:36]     linux_process.cpp(446) - Log     - Changed word to ffffffffffffffcc and re-poked in process 1255636. Continuing child
Core     PID 1255489: [16:49:37]     linux_process.cpp(456) - Error   - Didn't hit breakpoint in PID 1255636 (0)
```
Let me know if you'd like a separate bug for this and I'll write it up.

**Comment by baldurk** [comment]
Please do not comment on closed bugs, open a new issue with reproduction steps. Also the message about `wrong ELF class: ELFCLASS64: ignored` suggests that you're running 32-bit code, before opening a bug make sure that you are not doing that because only 64-bit is supported on linux.
