### ISSUE TITLE
Using VK_EXT_extended_dynamic_state seems to invert depth in captures

### ISSUE THREAD

**Issue by neonmoe** [baldurk/renderdoc#2546]
## Description

RenderDoc's Texture Viewer view of my application's swapchain image shows the back wall of the sponza scene. I would expect to see the sponza scene with everything else in front of the back wall, as the running application renders it. I can get the Texture Viewer to show the expected image by changing my pipeline's depth compare op from GREATER_OR_EQUAL to LESS_THAN_EQUAL and the clear value from 0 to 1, though this causes the actual running program to draw the back wall in front of everything, exactly what RenderDoc does with the GREATER_OR_EQUAL. The thumbnail shown in the "Captures collected" list does show the scene as it's rendered in my application, i.e. just a regular old sponza scene with the expected drawing order.

Oddly enough, when viewing any of the vkCmdDrawIndexed calls, and inspecting the depth framebuffer's pixel history, the pixel history shows a different, probably the correct depth value. For example, I just clicked a random pixel, and according to the pixel history, it's gone from 0.00 to 0.11283 in 3 draws, and then one draw failed the depth test. However, the texture coordinate & value information at the bottom of the texture view tells me that the depth is 0.90509. Screenshot of that view: 
![image](https://user-images.githubusercontent.com/22432472/163274051-f72a4578-441a-40f0-aa78-e69d97ec7eb2.png)

This started happening after I switched to dynamic viewport and scissor. If it's of any use, the commit in my renderer is [here](https://git.neon.moe/neon/neonvk/commit/dd887f7ed976fb2aa14f6d5b25aa738958bc856a). It's in Rust, but all the Vulkan API calls are just bindings, so hopefully it's somewhat legible. As far as I understand though, I didn't really change anything except make the viewport and scissor dynamic with the VK_EXT_extended_dynamic_state extension.

Honestly, this is probably an issue related to my usage of the API, given that it's my first proper 3D renderer in Vulkan, but I can't seem to get the rendering to behave as expected by RenderDoc, so I'd honestly just like any pointers as to what to try here. Or maybe it is a bug in RenderDoc.

## Steps to reproduce

1. Open this capture in RenderDoc: https://misc.neon.moe/foo/not-working-post-dynamic-viewports.rdc (it's captured from the commit I linked above, so not my code's latest version, but right after I added the dynamic viewports which seemed to break depth)
2. Open the Texture Viewer tab.
3. Observe the back wall of the sponza scene, heh. For proof that the application really does render the sponza scene properly when running it regularly, you could run the application as well, I can provide binaries for Linux (and maybe Windows, haven't tested on it) if needed, but the code is here: https://git.neon.moe/neon/neonvk

For a comparison, I made a capture of the previous, working commit as well: https://misc.neon.moe/foo/working-pre-dynamic-viewports.rdc And just to be clear, while recording both of these captures, I saw the exact same scene in the actual running application window (the one seen in this capture).

## Environment

* RenderDoc version: Nightly 2022-04-12, c3ed881b9fe82832736a893769c83ee66dd0e090 according to the About window. Happens in the 1.19 release too.
* Operating System: Arch Linux (updated last night)
* Graphics API: Vulkan (1.3)
* Graphics drivers: Mesa 22.0.1
* GPU: AMD Radeon RX 6800 XT (or RADV SIENNA_CICHLID as mesa calls it)

**Comment by baldurk** [comment]
I can't reproduce this unfortunately. I tried with AMD on windows and on linux (with slightly different mesa version and GPU) and it displays correctly:

![image](https://user-images.githubusercontent.com/661798/163450461-1ad6bf37-15ab-4f66-b160-8f97c6adf1d7.png)

I'd suggest trying to build mesa from latest (which is what I was running) in case it's an issue that has been fixed, or trying on a different GPU.

**Comment by neonmoe** [comment]
Building mesa from source (22.2.0 at commit [c7eaf030687](https://gitlab.freedesktop.org/mesa/mesa/-/commit/c7eaf030687)) resulted in the same issue with the texture viewer showing the reversed depth, but clicking on the seemingly any "vkCmdDrawIndexed" call in the Event Browser caused the driver to crash (black screen, needed to reboot every time). Here's the kernel log [gpu-crash-log.txt](https://github.com/baldurk/renderdoc/files/8491701/gpu-crash-log.txt), but I don't see anything really useful there. Interestingly enough, the crashing issue happens even with an older build of my renderer, without the dynamic viewport.

The application still runs fine, and I can make a new capture which still has the issue: https://misc.neon.moe/foo/not-working-on-mesa-latest.rdc This also has the same crashing issue on the latest git mesa.

It also occurred to me that this might be a Wayland/X11 thing, but I could reproduce the issue on X11 as well, unfortunately.

**Comment by baldurk** [comment]
Just to clarify, mesa latest crashes on selecting a draw for you regardless (on the `working` and `not-working` captures from before), where you didn't see that in either case for mesa 22.0.1? I can't reproduce that at least on my RX 480 system I can easily test on, it works fine for me (though the `not-working` capture can't open on the older mesa I was running as it predated the existence of the VK_EXT_extended_dynamic_state extension).

Given that, this sounds like it would be best to report as a mesa bug, it's possible the crash regression and your inverted depth is related. Bisecting where it started crashing might be a good idea to help the mesa developers. Right now though I don't see a RenderDoc issue here currently since it's working for me on mesa and AMD windows, and validation doesn't pick up anything relevant nor do I see any issues manually by eye.

You could also try using plain dynamic viewports/scissors from core vulkan 1.0 without the dynamic count extension, just as an experiment for another data point.

**Comment by neonmoe** [comment]
> Just to clarify, mesa latest crashes on selecting a draw for you regardless (on the working and not-working captures from before), where you didn't see that in either case for mesa 22.0.1?

Yep. I tried plain dynamic viewports/scissors too, and they still reproduce the depth issue. It's definitely about the dynamic viewports too, as I could make the issue go away by simply commenting out the dynamic states and vkCmdSetViewport/Scissor calls. But yeah, agreed, this does seem like a mesa issue, probably related to the new(ish) 6000-series cards.
