### ISSUE TITLE
Application crashes when running through renderdoc

### ISSUE THREAD

**Issue by Muzza** [baldurk/renderdoc#316]
My app has started crashing when running it through RenderDoc after I integrated Nvidia VXGI. Whilst investigating I've found that the VXGI sample app will also crash when running through RenderDoc.
The code is available here: https://developer.nvidia.com/vxgi  (I'm running the GlobalIllumination sample)

The first crash occurs when the App calls `GetDevice` on a `ID3D11DeviceContext` (this is in the constructor of `IRendererInterfaceD3D11`)
I can't see any obvious reason why this would only crash when using RenderDoc?

If I work around it by passing the device pointer through to bypass the `GetDevice` call it simply crashes later in one of the Nvidia closed source DLL's. In my own App, Renderdoc runs the game ok, but as soon as I capture a frame the App immediately exits.

I'm not sure if this is a bug with Renderdoc, or something that the Nvidia code is doing. Any ideas how I might be able to track this down? I don't want to lose the ability to analyze captures!

**Comment by baldurk** [comment]
This was a subtle one but not too difficult to track down, since someone else also ran into the problem and had found that it only happened for v0.30 - v0.29 was fine.

Turns out it was clang-format rearranging headers, that meant the GetDevice() function was returning an invalid pointer because it didn't have visibility of the wrapped device class's definition anymore. Phew!

Anyway, I think hopefully the GetDevice() problem is fixed now, but let me know if you maybe have other problems capturing VXGI.

**Comment by Muzza** [comment]
Thanks, I've just tried it and it does fix the GetDevice crash, but it still crashes about 50% of the time when I press F12 to do a capture - both in my own app and the sample app.

**Comment by baldurk** [comment]
Hmm, I downloaded the VXGI sample and if I run then I don't get any crashes when capturing - I've run many times and done multiple captures each time without a problem.

I presume you've built RenderDoc locally if you're able to test the change that quickly - how exactly are you running the sample? Did you build release/x64 or some other target? If you have it built locally is there any chance you could attach to it and see what the callstack and cause of crash is?

**Comment by Muzza** [comment]
Yes I built RenderDoc locally. I've just tried again, and using x64 build (both RenderDoc and the VXGI sample) works fine, but using x86 (both RenderDoc and VXGI) crashes about 50% of the time for me.

**Comment by Muzza** [comment]
ok, I managed to get a callstack of the crash and it's in Serialiser::AllocAlignedBuffer trying to allocate 3GB!
So I guess it's just a case of this App using too much memory to be captured using 32bit RenderDoc. I'll stick with x64.

**Comment by baldurk** [comment]
OK, glad you got it sorted! Yeh applications with hefty GPU usage really need to stick to x64. If you think it shouldn't be using that much memory though feel free to open another issue with more details.
