### ISSUE TITLE
Buffer VkMemoryRequirements has high-order memory type bits set for non-existent memory types.

### ISSUE THREAD

**Issue by warp-10** [baldurk/renderdoc#627]
When running through the RenderDoc UI, `VkMemoryRequirements::memoryTypeBits` will sometimes have high-order bits set for memory types that are not reported through `VkPhysicalDeviceMemoryProperties` (in fact, all high order bits are set).

Repeatable with the following options for the buffer:

    VK_BUFFER_USAGE_TRANSFER_SRC_BIT
    | VK_BUFFER_USAGE_TRANSFER_DST_BIT
    | VK_BUFFER_USAGE_VERTEX_BUFFER_BIT
    | VK_BUFFER_USAGE_INDEX_BUFFER_BIT

**Comment by baldurk** [comment]
Ah I see the problem, it's leftovers from the memory index remapping code. It's currently just an identity mapping but after all the memory types (say the first 10 bits) all the other indices are 0, so if bit 0 is set then all high-order bits are set.

**Comment by baldurk** [comment]
Can you please test with that commit? I think it should resolve the problem. Either building renderdoc locally or checking the next nightly build.

**Comment by warp-10** [comment]
memoryTypeBits looks OK

- BUT -

Now hitting a breakpoint @: Line 215, vk_manager.cpp.
"Couldn't get ID for image %p in barrier"
t.image == nullptr

Note: I'm trying to just view a single image - there is no rendering set up, just submitting transfer operations. I'm naming the object as per the instructions on the website (debug marker).

**Comment by warp-10** [comment]
Also, on instance destruction, at line 53 in vk_manager.h

    RDCASSERT(m_ResourceRecords.empty())
    RDCASSERT(m_CurrentResourceMap.empty())

Both containers are non-empty.

**Comment by baldurk** [comment]
The first error indicates that there's a `VkImageMemoryBarrier` somewhere with a image handle that's `NULL`, which is invalid. Can you check you're not submitting anything like that?

The second assertions indicate leaking resources - it's harmless in itself but all resources should be destroyed before destroying the instance.

**Comment by warp-10** [comment]
Understood about the resources.
And yes, it looks like I was passing in a null image handle - my bad.

However, the image still does not show up in the texture viewer (I can move this to another issue, if that would be appropriate).

**Comment by baldurk** [comment]
Yes I think that's best as the original bug seems to be solved. I'll need some more information to reproduce that bug - at least a capture or ideally the program that you're running, if you're able to share that.
